# Generated by Django 5.1.1 on 2024-09-12 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('submission_files', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('submission_links', models.URLField(blank=True, null=True)),
                ('submission_images', models.ImageField(blank=True, null=True, upload_to='submissions/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='hackathon.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submsission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
