# Generated by Django 5.1.1 on 2024-09-12 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('background_image', models.ImageField(upload_to='hackathons/backgrounds/')),
                ('hackathon_image', models.ImageField(upload_to='hackathons/images/')),
                ('Submission_Type', models.CharField(choices=[('images', 'Images'), ('file', 'File'), ('link', 'Link')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reward_prize', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registered_users', models.ManyToManyField(related_name='registered_hackathons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
